name: Build Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - uses: actions/checkout@v2
      - run: echo "[aurto]\nSigLevel = Optional\nServer = https://aur.raccube.net/" >> /etc/pacman.conf
      - name: Install dependencies
        run: pacman -Syu --noconfirm gptfdisk arch-install-scripts git qemu-user-static-bin archlinuxarm-keyring
      - name: Build ODroid image
        run: sudo ./build.py odroid.img
      - name: Compress image
        run: zstd odroid.img
      - name: Publish compressed image
        uses: actions/upload-artifact@v2
        with:
          name: ODroid Image
          path: odroid.img.zst
